name: RDP via Serveo (No Ngrok)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install desktop & xrdp
      run: |
        sudo apt update
        sudo apt install xfce4 xfce4-goodies xrdp openssh-client -y
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "rdpuser:rdppass" | sudo chpasswd
        sudo useradd -m rdpuser || true
        sudo usermod -aG sudo rdpuser

    - name: Tunnel via Serveo (port forwarding)
      run: |
        ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net &
        sleep 10
        curl https://serveo.net  # ini akan menampilkan subdomain acak yang aktif
