name: RDP via localhost.run (Gratis, Tanpa Kartu)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Desktop & xrdp
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp openssh-client
        sudo useradd -m rdpuser || true
        echo "rdpuser:rdppass" | sudo chpasswd
        sudo usermod -aG sudo rdpuser
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Start TCP Tunnel with localhost.run
      run: |
        echo "TUNNEL URL AKAN MUNCUL DI BAWAH INI:"
        ssh -o StrictHostKeyChecking=no -R 2222:localhost:3389 ssh.localhost.run
