name: RDP via Serveo (No Ngrok, No Kartu)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install desktop & xrdp
      run: |
        sudo apt update
        sudo apt install xfce4 xfce4-goodies xrdp openssh-client -y
        sudo useradd -m rdpuser || true
        echo "rdpuser:rdppass" | sudo chpasswd
        sudo usermod -aG sudo rdpuser
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Setup tunnel with Serveo
      run: |
        ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net &
        sleep 10
        echo "Tunggu sebentar, lalu buka bagian log ini untuk melihat alamat RDP-nya (serveo.net:PORT)"
        curl https://serveo.net
